name = "haikpheus"
main = "worker.js"
compatibility_date = "2026-07-20"

[[d1_databases]]
binding = "HAIKPHEUS_DB"
database_name = "haikpheus-state"
database_id = "b57a876d-70dc-4783-a42e-c6fbf0e8b1e1"
